# Generated by tools/pipeline.py generate.
{
  "otter-assist" = {
    pin = "otter_assist";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-tools-core" "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-assistant" = {
    pin = "otter_assistant";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-geo" "otter-render" "otter-theme" "otter-tools-core" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = true;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-bar" = {
    pin = "otter_bar";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-bench" = {
    pin = "otter_bench";
    snapshotVersion = "0.1.6";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "EGL" "GL" "GLX" "vulkan" "wayland-client" ];
  };
  "otter-browser" = {
    pin = "otter_browser";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "WPEWebKit-2.0" "atk-1.0" "atk-bridge-2.0" "drm" "gio-2.0" "glib-2.0" "gobject-2.0" "libsecret-1" "soup-3.0" "sqlite3" "wayland-client" "xkbcommon" ];
  };
  "otter-cal" = {
    pin = "otter_cal";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-tools-core" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-calc" = {
    pin = "otter_calc";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-tools-core" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-clicker" = {
    pin = "otter_clicker";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-theme" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-clip" = {
    pin = "otter_clip";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-tools-core" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-conf" = {
    pin = "otter_conf";
    snapshotVersion = "1.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-config-types" = {
    pin = "otter_config_types";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-geo" "otter-render" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-cue" = {
    pin = "otter_cue";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-desktop" "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-desktop" = {
    pin = "otter_desktop";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-utils" ];
    hasRemoteDeps = true;
    systemLibraries = [ "jemalloc" "mimalloc" "pam" "pthread" "rt" ];
  };
  "otter-dock" = {
    pin = "otter_dock";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-emoji" = {
    pin = "otter_emoji";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-tools-core" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-examples" = {
    pin = "otter_examples";
    snapshotVersion = "0.0.1";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-files" = {
    pin = "otter_files";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "ssh" "wayland-client" "webp" "xkbcommon" ];
  };
  "otter-first-setup" = {
    pin = "otter_first_setup";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-pkg" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-geo" = {
    pin = "otter_geo";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [  ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-greeter" = {
    pin = "otter_greeter";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = true;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-hypr" = {
    pin = "otter_hypr";
    snapshotVersion = "0.1.0";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-idle" = {
    pin = "otter_idle";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-installer" = {
    pin = "otter_installer";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-jade" = {
    pin = "otter_jade";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-keybindhelp" = {
    pin = "otter_keybindhelp";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-launcher" = {
    pin = "otter_launcher";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-tools-core" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-lock" = {
    pin = "otter_lock";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = true;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-logout" = {
    pin = "otter_logout";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-monitor" = {
    pin = "otter_monitor";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-nightlight" = {
    pin = "otter_nightlight";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-tools-core" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-note" = {
    pin = "otter_note";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-render" "otter-theme" "otter-tools-core" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-notifications" = {
    pin = "otter_notifications";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-osd" = {
    pin = "otter_osd";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-overview" = {
    pin = "otter_overview";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-pick" = {
    pin = "otter_pick";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-render" "otter-theme" "otter-tools-core" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-pkg" = {
    pin = "otter_pkg";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "apt-pkg" "wayland-client" "xkbcommon" ];
  };
  "otter-polkit" = {
    pin = "otter_polkit";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-rec" = {
    pin = "otter_rec";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-desktop" "otter-theme" "otter-tools-core" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "dl" "egl" "glesv2" "libavcodec" "libavformat" "libavutil" "libdrm" "libswscale" "wayland-client" ];
  };
  "otter-render" = {
    pin = "otter_render";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-utils" ];
    hasRemoteDeps = true;
    systemLibraries = [ "fontconfig" "jemalloc" "mimalloc" ];
  };
  "otter-screenshot" = {
    pin = "otter_screenshot";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-desktop" "otter-render" "otter-theme" "otter-tools-core" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-search" = {
    pin = "otter_search";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-tools-core" "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-settings" = {
    pin = "otter_settings";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-tools-core" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-shell-plugins" = {
    pin = "otter_shell_plugins";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-desktop" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-shot" = {
    pin = "otter_shot";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-tools-core" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-taskbar" = {
    pin = "otter_taskbar";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-term" = {
    pin = "otter_term";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-vte" "otter-wayland" ];
    hasRemoteDeps = true;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-theme" = {
    pin = "otter_theme";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-geo" "otter-render" "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-theme-gen" = {
    pin = "otter_theme_gen";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-render" "otter-theme" "otter-tools-core" "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-timer" = {
    pin = "otter_timer";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-tools-core" "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-tools-core" = {
    pin = "otter_tools_core";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-transcribe" = {
    pin = "otter_transcribe";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "dl" "pthread" "wayland-client" "xkbcommon" ];
  };
  "otter-ui" = {
    pin = "otter_ui";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-desktop" "otter-geo" "otter-render" "otter-theme" "otter-tools-core" "otter-utils" "otter-vte" "otter-wayland" ];
    hasRemoteDeps = true;
    systemLibraries = [ "fontconfig" "pam" "wayland-client" "xkbcommon" ];
  };
  "otter-utils" = {
    pin = "otter_utils";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [  ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-vox" = {
    pin = "otter_vox";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-desktop" "otter-tools-core" "otter-utils" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-vte" = {
    pin = "otter_vte";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-render" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
  "otter-wallpaper" = {
    pin = "otter_wallpaper";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-conf" "otter-config-types" "otter-geo" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" ];
  };
  "otter-wayland" = {
    pin = "otter_wayland";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-render" "otter-utils" ];
    hasRemoteDeps = true;
    systemLibraries = [ "jemalloc" "mimalloc" "wayland-client" "xkbcommon" ];
  };
  "otter-weather" = {
    pin = "otter_weather";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-render" "otter-theme" "otter-tools-core" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [ "wayland-client" "xkbcommon" ];
  };
  "otter-welcome" = {
    pin = "otter_welcome";
    snapshotVersion = "0.11.113";
    minimumZigVersion = "0.16.0";
    directDeps = [ "otter-geo" "otter-pkg" "otter-render" "otter-theme" "otter-ui" "otter-utils" "otter-wayland" ];
    hasRemoteDeps = false;
    systemLibraries = [  ];
  };
}
