# generated by tools/gen-locks.sh; do not edit by hand
args@{
  fetchgit,
  fetchurl,
  fetchzip,
  gnutar,
  lib,
  linkFarm,
  runCommandLocal,
  zig,
}:

(import ./mk-lock.nix args) [
  "N-V-__8AAEgZ3gDiNoXcVjyqu1oc89Qzq1N9lay3xr4y8rRX"
  "N-V-__8AAMV2BgB9aKHnchADe5onASuvEqAeRRO7Ai1oTuzW"
  "aro-0.0.0-JSD1Qi7QNgDnfcrdEJf82v3o6MhZySjYVrtdfEf3E4Se"
  "translate_c-0.0.0-Q_BUWpf0BgAwrh5AM-acJcslN_YPEhcoCVKbbNjwuUTJ"
]
