# generated by tools/gen-locks.sh; do not edit by hand
args@{
  fetchgit,
  fetchurl,
  fetchzip,
  gnutar,
  lib,
  linkFarm,
  runCommandLocal,
  zig,
}:

(import ./mk-lock.nix args) [
  "zeit-0.6.0-5I6bk7q6AgBdMJxze3D4l9ylQhkviQ_BX9FigDt13MFn"
]
