# generated by tools/pipeline.py lock; do not edit by hand
args@{
  fetchgit, fetchurl, fetchzip, gnutar, lib, linkFarm, runCommandLocal, zig,
}:

(import ./mk-lock.nix args) [
  "zhl-1.0.0-6W1vbr6gTgFLwri8jcX_C_qHgolHrZLmWtQPmYJz52oU"
]
