# generated by tools/gen-locks.sh; do not edit by hand
args@{
  fetchgit,
  fetchurl,
  fetchzip,
  gnutar,
  lib,
  linkFarm,
  runCommandLocal,
  zig,
}:

(import ./mk-lock.nix args) [
  "wayland-0.6.0-dev-lQa1krD8AQBlMqwuhAMJjPQKXvpRByZBxxqMVAZ7yzbG"
]
