# generated by tools/gen-locks.sh; do not edit by hand

{ fetchgit, fetchurl, fetchzip }:

{
  "N-V-__8AACSdYAB_UbYSe21ZcD-qFBX7twJ4mRDPTrekTXQF" = {
    source = fetchurl {
      url = "https://github.com/glennrp/libpng/archive/refs/tags/v1.6.57.tar.gz";
      hash = "sha256-TLt7B0btwWg8lYGzczZelVEzt/EkPxcbfRU1tEFd/ts=";
    };
    sourceIsArchive = true;
  };

  "N-V-__8AAEgZ3gDiNoXcVjyqu1oc89Qzq1N9lay3xr4y8rRX" = {
    source = fetchgit {
      url = "https://gitlab.freedesktop.org/pipewire/pipewire.git";
      rev = "cc3d0d1191266b263f6d0fa03fce1d1ef57151cc";
      fetchSubmodules = false;
      hash = "sha256-zD0PYtZsiU+tZUpVBKofjGVQyO/68eIZP7DqBQHUGJk=";
    };
  };

  "N-V-__8AAI4ANwDM8MWhHTUFLKfvLE_n2NQk6mh0sFDzhTqO" = {
    source = fetchurl {
      url = "https://github.com/madler/zlib/archive/refs/tags/v1.3.2.tar.gz";
      hash = "sha256-uZoLhsC6k2DsfnjE8eQ7HL3x5pNsj6D2g1wM1pSklaE=";
    };
    sourceIsArchive = true;
  };

  "N-V-__8AAJ5J4QV1Qw46kP_V9eNRdRVk9Cp65YNLuECHurpK" = {
    source = fetchurl {
      url = "https://github.com/harfbuzz/harfbuzz/archive/refs/tags/14.1.0.tar.gz";
      hash = "sha256-ne/+nd7Tw2fH0IJl/QpkGT+tUFo2KkiJ2JhWjBzUaBI=";
    };
    sourceIsArchive = true;
  };

  "N-V-__8AAJo-LAHFNfa0p0oMQqmwlBEAZMOeo03azXgrKLTT" = {
    source = fetchurl {
      url = "https://download.savannah.gnu.org/releases/freetype/freetype-2.14.3.tar.xz";
      hash = "sha256-NrxPHMQTM1No7mVsQq/KZcWjmH6HaMwozxG6d154Wl8=";
    };
    sourceIsArchive = true;
  };

  "N-V-__8AALTJcQJ3hosujokSgxYTsa3q1mDZ2dasYhuJwaOV" = {
    source = fetchurl {
      url = "https://www.unicode.org/Public/zipped/16.0.0/UCD.zip";
      hash = "sha256-yG3YHysUpDsMwGSqX4mqckE4aAHjXFnHmE5XmDJjTrI=";
    };
    sourceIsArchive = true;
  };

  "N-V-__8AAMV2BgB9aKHnchADe5onASuvEqAeRRO7Ai1oTuzW" = {
    source = fetchurl {
      url = "https://github.com/allyourcodebase/valgrind.h/archive/refs/tags/3.23.0.tar.gz";
      hash = "sha256-MLyxrVhfqhibCEuDOL3hSUJbXJMEi0jLxDO46Xt6IL4=";
    };
    sourceIsArchive = true;
  };

  "aro-0.0.0-JSD1Qi7QNgDnfcrdEJf82v3o6MhZySjYVrtdfEf3E4Se" = {
    source = fetchgit {
      url = "https://github.com/Vexu/arocc";
      rev = "5f5a050569a95ecc40a426f0c3666ae7ef987ede";
      fetchSubmodules = false;
      hash = "sha256-f8Z0SXWx5Uia2TCMB5SUpcO8+xUnaWk32Oknva7xcxw=";
    };
  };

  "freetype-2.14.3-C3-WdXSKAAB-kHs4qgRoeoFnRkNQn6M_SSlUGZ6ywgBQ" = {
    source = fetchgit {
      url = "https://github.com/allyourcodebase/freetype";
      rev = "884fd2235e6ae1ec4306eda30b3259f20930ed2e";
      fetchSubmodules = false;
      hash = "sha256-G8tz/q/u5iMrHqM4DAeFECpIkgLHRbQcvLtHgaObghE=";
    };
  };

  "harfbuzz-14.1.0-Ip1VAuGZAAC1jdxPHOMPoHyi-50Hm_q4bveaVflELHGw" = {
    source = fetchgit {
      url = "https://github.com/allyourcodebase/harfbuzz";
      rev = "d055840ecefefcd57f5ddeb2fa8c83fafed1a40b";
      fetchSubmodules = false;
      hash = "sha256-SuJqQhdieTHo47phya6PFC9Euo8USTrTHaw5cPqRt7k=";
    };
  };

  "libpng-1.6.57-oiaFGuYqAAB3CK1mjIzXHn2Z3EVV9okuko-VH23OOSV_" = {
    source = fetchgit {
      url = "https://github.com/allyourcodebase/libpng";
      rev = "e123eca2140de78f1017a46c24e330fb3024fc58";
      fetchSubmodules = false;
      hash = "sha256-Kwa87ZpLaqe+iTBWEwDduu19h6mjBEDMggN1wz1Bqu4=";
    };
  };

  "translate_c-0.0.0-Q_BUWpf0BgAwrh5AM-acJcslN_YPEhcoCVKbbNjwuUTJ" = {
    source = fetchgit {
      url = "https://codeberg.org/ziglang/translate-c";
      rev = "46b5609b5ac4c0a896217d1d984f3ae50e4810b5";
      fetchSubmodules = false;
      hash = "sha256-ZQf1yyG7Z2bVOVQskLBmTdZQ43/xKltgwra+AZirvO4=";
    };
  };

  "uucode-0.2.0-ZZjBPlK5VADj7fdoq7G8LIHzD5o6FSkcBXXrRWr4jnrA" = {
    source = fetchgit {
      url = "https://github.com/jacobsandlund/uucode";
      rev = "2826a37a4562284fdacd8fa029d49509cc9bffcd";
      fetchSubmodules = false;
      hash = "sha256-R5RXW5tWIaDq5JOF2+oWd5YOYOyns6WH7f687WE+b20=";
    };
  };

  "wayland-0.6.0-dev-lQa1krD8AQBlMqwuhAMJjPQKXvpRByZBxxqMVAZ7yzbG" = {
    source = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland";
      rev = "4a150a04f76f7329e80280661355c04328369d1f";
      fetchSubmodules = false;
      hash = "sha256-B5nA05xYm6iRDDRFC2KUbhBCtjwmApka+BcDCZRssfw=";
    };
  };

  "zeit-0.6.0-5I6bk7q6AgBdMJxze3D4l9ylQhkviQ_BX9FigDt13MFn" = {
    source = fetchgit {
      url = "https://github.com/rockorager/zeit";
      rev = "2a79678e05e4e82cd4efd4fd6b754dcf029c3a64";
      fetchSubmodules = false;
      hash = "sha256-LFNg8yu82OcQ+Yyxw1bTotjW18oVhNiYrFGIE/7WWR4=";
    };
  };

  "zhl-1.0.0-6W1vbr6gTgFLwri8jcX_C_qHgolHrZLmWtQPmYJz52oU" = {
    source = fetchurl {
      url = "https://github.com/ferrreo/zhl/archive/refs/tags/v0.0.1.tar.gz";
      hash = "sha256-EJdcR1cjMZm1zxPe3OoQFpKBHagPudrLGytquBblNqE=";
    };
    sourceIsArchive = true;
  };

  "zlib-1.3.2-ZZQ7lc8NAAAHm9MDfplvwoesXvk4tVm6VCsiI8KnIbT0" = {
    source = fetchgit {
      url = "https://github.com/allyourcodebase/zlib";
      rev = "d3b5519d3b73616a6bfece0712f080029d2a9244";
      fetchSubmodules = false;
      hash = "sha256-iTGFcAvz1Qx/R4Am8N9UcFiLm2zfZJEXSMbRjccVdbo=";
    };
  };

}
